version: "3.8"

volumes:
  pgdata:
    external: true
  esdata:
    external: true

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 6379:6379

  postgres:
    image: postgres:11-alpine
    container_name: postgres
    restart: unless-stopped
    network_mode: bridge
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:6.7.2
    container_name: elasticsearch
    restart: unless-stopped
    network_mode: bridge
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
