version: "3.8"

volumes:
  pgdata:
    external: true
  esdata:
    external: true
  mongodata:
    external: true

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 6379:6379

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    network_mode: bridge
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:4
    container_name: mongo
    restart: unless-stopped
    network_mode: bridge
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - '27017-27019:27017-27019'

  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    restart: unless-stopped
    network_mode: bridge
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
